### ISSUE TITLE
Example code in documentation.

### ISSUE THREAD

**Issue by bradllj** [getryft/spark-ryft-connector#108]
In the Ryft document Ryft One Spark Integration there is a section called:

7: Example: Incoming Twitter Feed & Spark

It has a code sample for Zeppelin. But it is a partial screen shot. The code is not complete.

Where is this code? Can it be added to the examples in this repository?
thanks

**Comment by adleyva** [comment]
example added to project.

`https://github.com/getryft/spark-ryft-connector/blob/master/examples/src/main/scala/com/ryft/spark/connector/examples/TwitterNFLExample.scala`
