### ISSUE TITLE
Implement Release Artifacts publishing to GitHub

### ISSUE THREAD

**Issue by demon-xxi** [getryft/spark-ryft-connector#34]
Automatically publish jar files for every tag on master branch

**Comment by sprokopets** [comment]
Assembled JAR files built against Scala 2.10.5 and 2.11.7 version are uploaded only for tagged commit, example of automatic release of artifacts: https://github.com/getryft/spark-ryft-connector/releases/tag/0.4.0.1

More details regarding Travis CI deployment to Github: https://docs.travis-ci.com/user/deployment/, https://docs.travis-ci.com/user/deployment/releases
