### ISSUE TITLE
Maven Central support

### ISSUE THREAD

**Issue by demon-xxi** [getryft/spark-ryft-connector#35]
Configure Maven Central account and configure automatic artifacts upload on every release tag on master branch

**Comment by sprokopets** [comment]
Configured Travis CI to automatically release artifacts to Maven Central repository for tagged commit on master branch. 
Modules were automatically released to Maven Central repository for multiple Scala version: 2.10 -  http://search.maven.org/#artifactdetails%7Ccom.ryft%7Cspark-ryft-connector_2.10%7C0.4.0%7C, 2.11 - http://search.maven.org/#artifactdetails%7Ccom.ryft%7Cspark-ryft-connector_2.11%7C0.4.0%7C

Articled and documentation for reference:
- http://www.scala-sbt.org/release/docs/Using-Sonatype.html
- http://central.sonatype.org/pages/ossrh-guide.html#deployment
- http://central.sonatype.org/pages/requirements.html
- http://central.sonatype.org/pages/working-with-pgp-signatures.html
- http://central.sonatype.org/pages/releasing-the-deployment.html#login-into-ossrh
- https://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci

SBT Plugins:
- https://github.com/sbt/sbt-pgp
- https://github.com/xerial/sbt-sonatype
